name: EventEase

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Saliezaara@2005#
    ports:
      - "1433:1433"
